### PR TITLE
Edited Gases based on wikipedia's stats

### PR DESCRIPTION
**Pull request by silver2127**
Helium is a anti greenhouse gas. Ozone is a very powerful greenhouse gas.

### CODE REVIEW

**Comment by se5a** [comment]
What numbers do these represent?
since we don't have greenhouse effect actually in the game yet, I've not even looked at how to model it.

**Comment by silver2127** [comment]
I guess you'd have to ask the original author. I based my values given the existing values for methane and Anti Greenhouse Gasses so it would be consistent.

**Comment by silver2127** [comment]
There is probably some scientific measurement for this I will see if I can find it.

**Comment by se5a** [comment]
if I were to sit down and do the greenhouse stuff now, likely I'd look at a percentage of how much energy the gas absorbed vs reflected or let through. 
I'm not going to sit down and do it now though. too many other things which need doing first.

**Comment by silver2127** [comment]
Ok.

**Comment by se5a** [comment]
I mean, if you want to try find those values, that could work for the future. at the moment though the current values are just arbitrary.

**Comment by silver2127** [comment]
Yea. I asked a friend of mine who does chemistry if they have anything official for this or what he would use. I'll get back to you when he responds.

**Pull request closed without merging**
