### PR TITLE
Additional tests and revision to code in OrbitalMath

### PR DESCRIPTION
**Pull request by Maeverathla**
I'm working through understanding the math in the Orbital namespace. This pull request attempts to improve stability of some of the low level code, Vector3, Angle, and GeneralMath most specifically. This is done through:

* Adding more tests wherever I was working
* Refactoring code where common-sense tests fail
  * The clearest example of this is Vector3.!=, which did not correctly return true in all cases
  * Additionally, Angle.DifferenceBetweenXXXX did not seem to consistently return a correctly normalized number, so I rewrote it using the normalization method
* Refactoring to align with similar functionality in other codebases
  * Vector3 has been tweaked to be closer to the System.Numerics.Vector3 interface, specifically by changing invocations of static Magnitude to call non-static Length. I am not sure which version of .NET is currently being used, but assuming it's later than 4.6, I would recommend moving anything not part of the standard Vector3 to GeneralMath and using the library version
  * SelectFromRange has been renamed to Lerp as this method performs a linear interpolation. Lerp was used as it aligns with the method name in System.Numerics.Vector3, and so would align with the naming convention in the event the standard class was used as the Vector3 implementation 
  * Angle normalization was changed to return values in the range (-pi to pi] or (-180 to 180], so every angle now has exactly one normalized value
* Typo hunting and some magic number removal
  * Vector3 constructors have been replaced with static calls where applicable, for example Vector3.Zero instead of new Vector3(0,0,0)
  * Some magic number-unit conversions have been replaced with references to UniversalConstants 
  * Some redundant computation has been replaced with references to already-calculated values

Comments on these changes welcome. So far these should not have changed the values of any calculations, beyond the restriction on angle value. If they do that is likely a sign I made a mistake in one of my changes.

-Kenobi

### CODE REVIEW

**Comment by se5a** [comment]
Woah, sounds good!
I'll have a closer look when I get home from work. 
One other thing I want to look at in this space is merging orbitMath and orbitalMath namespaces. One just extends the other and handles higher level data inputs. These should remain in their separate projects, but having the same namespace I think should clean up some of the higher level code.

**Comment by se5a** [comment]
I've not looked had a chance to look too deeply yet, but I'm getting a NaN in OrbitDB.CalculateExtendedParameters when running this. 
While looking at this I've also noticed that there are some places that need tidying up in this class too, ie conversions to AU then back again to metric, this will be an oversight from when I refactored everything to be stored in more consistent units. 

I'm a bit 50/50 on Magnitude vs length, I *think* Magnitude is more correct from mathematics terminology when talking about velocities and acceleration, which was probably what I was doing when I wrote it originally. I'm not adverse to the change though.

**Comment by Maeverathla** [comment]
I'll take a look at CalculateExtendedParameters after work today and see what's causing that.

As for Length/Magnitude, I prefer magnitude as well, it's more general terminology for anything a vector could represent and is used in Unity's vector structs. But System.Numerics.Vector2/3 use Length and LengthSquared and one of my goals was to mind l mimic their interface.

And finally on the units question, I haven't gotten a good sense whether most of the simulation calculations are done using meters or AU. I expect there are precision issues with both approaches in various contexts, which is why there are some methods with decimal options. IMHO switching back and forth in one method isn't really a problem as it just adds two multiplications, but it is worth asking why there are two versions of the method.

**Comment by Maeverathla** [comment]
I think I got it, at least I don't get a NaN exception on my end anymore. `specificOrbitalEnergy` in `OrbitMath.KeplerFromPositionAndVelocity` was calculated as `Math.Pow(speed * speed, 2) * 0.5 - standardGravParam / position.Length();` which squared `speed` twice instead of once. This lead to `a` being calculated as a very small negative number, which was throwing things off.

**Comment by se5a** [comment]
Looks good my end with a quick test, will merge. 

Longer story with the units:
Distances used to be stored in AU, velocities in m/s mass in kg or T etc and it was all over the place, ended up causing lots of issues and math bugs that were hard to figure out with not having a consistent framework, I think originally we didn't want to restrict the size of the solar systems by using meters, but eventually i figured the trade off was worth it. 
I ended up going through and storing everything in SI units which made most calculations way easier to comprehend, and less prone to mistakes. 
While I got all (most?) of the actual data storage of these units, I didn't sit down and go through all the calculations that were already just working. 
To get through the refactor (would have been kind of big as you can imagine) I stored units in metric, then created a property which grabbed the stored SI field and converted it on the fly, existing code that used older units still looked to the property didn't break, and new code could use the more sensible SI units, and the refactor was (relatively) quick and easy. 
Calculations *should* be done in SI units unless there's good reason not to. 
Existing code using non SI units is likely just old code that works and noone got around to tidying it up. 
Most results for googling for "how do I calculate x" will be in SI units as well.

**Comment by se5a** [comment]
Thanks for looking at this stuff too, I'll admit a fair amount of my math is grabbing formula from the net and getting it working without fully understanding *exactly* what it's doing. my math is kind of terrible.

**Pull request merged**
