### PR TITLE
Readme instructions for MAC

### PR DESCRIPTION
**Pull request by PRDeving**

### CODE REVIEW

**Comment by se5a** [comment]
Might want to keep a note about rider in there. the linux version of monodevelop is currently extremely troublesome to get working correctly, the flatpack versions won't even run/debug the game due to how it's sandboxed.

**Comment by PRDeving** [comment]
Just built the project with Mono and Xamarin and everything went just fine, i suposed that 1 good setup would be better than 2 non-tested options.

Gonna check rider as soon as possible on mac too to see how it goes tho

**Comment by se5a** [comment]
yeah the mac version (xamarin) doesn't use flatpack and isn't sandboxed. 
(your PR removed all mention of Rider, even for linux)
I guess the comment about rider may have been a little confusing where it was placed, it was not meant to be specifically for mac, but for all platforms.

**Comment by PRDeving** [comment]
True, I thought both were related, sorry.

fixed

**Pull request merged**
