### PR TITLE
Refactor to remove _AU versions of IPosition attributes

### PR DESCRIPTION
**Pull request by Maeverathla**
Apologies for the massive number of commits and number of added lines, there was some rebasing shenanigans that ended up doubling the number from the original 47 commits and caused git to think I completely rewrote the SystemGen files (while in reality I touched only a few lines in each).

This pull request removes IPosition.AbsolutePosition_AU and RelativePosition_AU. Wherever possible, logic was rewritten to work in meters instead of AU. In places where this could not be done (mostly in the UI), calls to Distance.MToAU were used to convert at point of use. As a result, a lot of other AU-based code was pruned, consolidated, and shortened. There are still variables with _m and _AU suffixes hanging around, but their number is greatly reduced.

Hopefully this leaves the codebase almost entirely using meters when doing calculations.

### CODE REVIEW

**Comment by se5a** [comment]
Sounds good, I'm going to be away for the weekend, and pretty busy with work, will try have a look tonight but don't be surprised if it's not till next week.

**Comment by se5a** [comment]
took a quick look tonight, looks like earth is about 180 degrees from what it used to be, might not be a biggie but the ships around earth are not in the correct position. 
I'll have a look see if I can figure out why tomorrow.

**Comment by se5a** [comment]
This is how it looks in devbranch before the PR changes:
image

This is how it looks after the PR changes:
image

 - Phase of earth and some other planets are wrong (or at least not what they were, not sure I've checked the phase of the planets before are actually correct for the date, and if not it's ralitivly minor, the phase will creep out of real life due to patched cone 2 body only being so accurate).
 - Position of earths childeren are way out of position, you can see the distance recorded for Luna in the Debug panel as being 151.231 Mkm. 
 - Touch and Go's orbit line is not in the correct direction, it's in a retrograde orbit however the line shows a prograde orbit.

If I advance time 1s the child positions snap into the correct distances, which might give us a clue as to what is wrong with that one:
image


For number 2 problem, I thought initially that maybe the positions in the data was getting mangled at creation, but that doesn't appear to be the case from a *quick* look in the Factories/SystemGen/SolEntities files.
Looking at what's going on though:
 - the orbit lines are still around earth and match the correct distances
 - the positions snap back when advancing time 
I'm guessing the problem is likely to be somewhere in the UI code (this is likely the case for Touch and Go's orbit line as well).

This is as far as I've got in trouble shooting this, and I've got a lunch date to get to, so I'll have another look later this arvo hopefuly.

**Comment by Maeverathla** [comment]
I'll take a look tomorrow when I'm back at my computer. Hopefully it's just a missed minus sign somewhere.

**Comment by se5a** [comment]
I was wrong on the data getting mangled at creation, I think that is exactly what's happening, probilby when the PositionDB gets created. since the PositionDB gets updated when the orbital sim runs it get's field when we advance time:

you can see in this panel the raw data from the positionDB:
image

you can get to this panel by 
- Hitting Escape (while game is running), 
- Select "Options" 
- Checking the "Show Pulsar Debug Window" checkbox. 
- From there you can select an entity by clicking on a name in the map screen, 
- In the debug window expand "Selected Entity", which will display basic info on the entity, 
- Expand the "DataBlob List",  
- Click ie Pulsar4X.ECSLib.PositionDB
This will then display the raw data that the datablob contains, it does all this via reflection which is quite nifty, though maybe not 100% stable, not guarantees it wont crash if you try examine a complicated datablob type that it doesn't like. 

Anyway, I'm thinking the position is wrong when creating the positionDB from here: https://github.com/angrywankenobi/Pulsar4x/blob/DevBranch/Pulsar4X/Pulsar4X.ECSLib/Factories/SystemGen/SolEntities/EarthAndLuna.cs#L64

**Comment by Maeverathla** [comment]
Alright, should be fixed now. As it turns out, I forgot to convert the MeanAnomaly that came into the planet constructor in degrees to radians before passing it along to the Kepler elements constructor.

**Comment by se5a** [comment]
Yeah that fixes the first problem but not the other two. 
Speaking of degrees and radians, would using turns be useful to us? https://www.computerenhance.com/p/turns-are-better-than-radians

**Comment by se5a** [comment]
Yeah this is correct: 
`PositionDB moonPositionDB = new PositionDB(moonOrbitDB.GetPosition(StaticRefLib.CurrentDateTime), sol.Guid, parentPlanet);`
since positionDB wants the relative position as an input there. not sure how it was working in the original code since we were adding the parent position then too... unless positionDB got changed from wanting absolute to relative? 
That fixes luna in the file I pointed to earlier. need to find where ships are going wrong it'll be the same problem, and in the ShipFactory.cs 
Gota get to work now though.

**Comment by se5a** [comment]
This will be the line for the ships position:
https://github.com/angrywankenobi/Pulsar4x/blob/DevBranch/Pulsar4X/Pulsar4X.ECSLib/Factories/ShipFactory.cs#L210
(remove the parent position from the position, should be relative not absolute)

That'll just leave the retrograde orbit lines not displaying correctly (ie Touch and Go).

**Comment by Maeverathla** [comment]
Thank you for cleaning up my mess, it's been a busy week and I haven't had much time to be at my computer. I'll make these changes after work.

Looking at the arguments for using turns over radians, I'm unconvinced for this application. First, this smells like a micro optimization that will cost more development time than it will gain in runtime. There are likely other places for efficiency improvements to look before this. Second, the references for orbital math all use radians so checking is easier if we stick in that space. Third, the C# sine function is written to receive radians. Writing a custom sine function isn't hard, but it's that much more code to maintain.

Overall I would recommend against the switch.

**Comment by Maeverathla** [comment]
Alright, those two should be fixed.

**Comment by se5a** [comment]
awesome!
last problem will likely be in the OrbitElipseBaseClass where it's checking the inclination to see if it should be a retrograde orbit or not. this is a bit funky with where I wrote a 3d library but only using it in 2d. 
last time I checked it looked like the entity had some inclination so I think the datablob is correct. 
anyway, gota get ready for work.

**Comment by se5a** [comment]
Ah yes I see the problem now I actualy look at it:
`if (_orbitDB.Inclination > 1/2 * Math.PI && _orbitDB.Inclination < 3/2 * Math.PI) `
should be:
`if (_orbitDB.Inclination > 1/2 * Math.PI && _orbitDB.Inclination < 3/2 * Math.PI * 2) `
or because I prefer multiplication:
`if (_orbitDB.Inclination > 0.5 * Math.PI && _orbitDB.Inclination < 1.5 * Math.PI) `

On the Turns thing: 
Yeah from a pure optimization pov I agree it's likely  not worth it, 
however from a parsing raw value of an angle you're trying to debug, turns are a lot nicer than radians, and arguably even easier to parse than degrees, then it feels a bit more worth it, for example the above problem might have been spotted a lot easiter:  
`if(_orbitDB.Inclination > 0.25 && _orbitDB.Inclination < 0.75 ) `.
Though whether it's worth it enough to actually do it is maybe not quite. 
It's not only the sin function, we'd have to custom write all the trig functions, and it'd be a big change to a lot of code.
Think we'll leave it for now. maybe in the future when I get around to separating OrbitMath off into it's own github repository

**Comment by Maeverathla** [comment]
Thank you again. I apologize that life has gotten in the way of me being more involved. I've made this change and pushed it. Should be good to merge

**Comment by se5a** [comment]
All good, you've made more progress than I have in the past couple of weeks, and since I've got a pretty good knowledge of the entire codebase I was able to make some good guesses at where the problems probably were.

**Pull request merged**
