### PR TITLE
Planetary Sensors

### PR DESCRIPTION
**Pull request by NathanH-**
This branch has populations integrated into the sensor model(able to detect, and be detected), and able to be damaged by weapons fire. The UI has also been filled our further and sensor bubbles can be displayed now. This is toggleable from the sensor tab on the SystemMap control form.

### CODE REVIEW

**Comment by se5a** [comment]
I'll merge this tomorrow. ;-)

**Comment by se5a** [comment]
Faction is getting pretty bloated Nathan, Can we move the sensor stuff into its own class?

**Comment by NathanH-** [comment]
I'll see what can be done on saturday, in the mean time the sensor model is finished, and regioned off fairly well.

**Comment by NathanH-** [comment]
Alright, done.

**Comment by NathanH-** [comment]
No issues with the commit have been raised. As to refactoring, I am aware of places in the code base that can stand to be refactored, but in the case of the sensor sweep function, I do not believe that much is meaningfully possible that can be done here aside from one-offs that rely on naive assumptions that may not turn out to be true later on. Given that the goal with the ECS branch will be to ultimately refactor this in any event, it is not something that I'll spend time on.

**Pull request merged**
